// Generated by npm run build. Do not edit.
var PRECACHE_VERSION = "e4490644b03131283e4d";
var PRECACHE_FILES = [
  "assets/app.js",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/maskable-512.png",
  "assets/input.js",
  "assets/pwa.js",
  "assets/style.css",
  "games.json",
  "games/snake/game.js",
  "games/snake/index.html",
  "games/template/game.js",
  "games/template/index.html",
  "games/wander/game.js",
  "games/wander/index.html",
  "index.html",
  "manifest.webmanifest",
  "offline.html",
  "sw.js",
  "vendor/THREE-LICENSE.txt",
  "vendor/three.min.js"
];
